common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', views.index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

import common.views
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
    path('mypage/', views.mypage, name='mypage'),
    path('loading3/', views.loading3, name='loading3'),
    path('write/', views.write_form, name='write'),
    path('loading_page/', views.loading, name='loading'),
    path('content/detail/<int:id>/', views.content_detail, name='content_detail'),
    # path('content/detail/<int:id>/', views.content_detail2, name='content_detail2'),
    path('content/create/', views.content_create, name='content_create'),
    path('lounge/', views.lounge, name='lounge'),
    path('answer/create/<int:content_id>/', views.answer_create, name='answer_create'),
    # path('like/<int:content_id>', views.likes, name='likes')
    # path('content/reco/<int:id>/', views.content_reco, name='content_reco')
    # path('answer_create/', views.answer_create, name='answer_create')
]

portfolio/models.py
from common.models import User
from django.db import models

# Create your models here.
class Content(models.Model):
    subject = models.CharField(max_length=200)
    username = models.CharField(max_length=50)
    content = models.TextField()
    content_for_posting = models.TextField()
    content_num = models.IntegerField(default=1)
    input_img = models.ImageField(upload_to='images/', blank=True, null=True)
    content_img = models.TextField(blank=True, null=True)
    reco_img = models.TextField(blank=True, null=True)
    like_count = models.TextField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(null=True)


class Answer(models.Model):
    username = models.CharField(max_length=50)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    context = models.TextField()
    create_date = models.DateTimeField()
    content_for_posting = models.TextField()

# class Like_profile(models.Model):
#     username = models.CharField(User)

portfolio/forms.py
from django import forms
from portfolio.models import Content, Answer

class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ['subject', 'username', 'content', 'input_img', 'content_img', 'like_count','content_for_posting']
        labels = {
            'subject': '제목',
            'username': '작성자',
            'content': '내용',
            'input_img': '입력이미지',
            'content_img': '이미지',
            'content_for_posting':'게시글 내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['context']
        labels = {
            'context': '답변내용',
        }

portfolio/views.py
from common.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from .models import Content, Answer
from .forms import ContentForm, AnswerForm
from django.core.paginator import Paginator
from pymongo import MongoClient
from .stable_diffusion import *
from .recommendation import *
import os, re
from django.db.models import Max
from django.db.models import Q

pymongo_connect = MongoClient("mongodb://localhost:27017")
pymongo_db = pymongo_connect["intoon"]
pymongo_col_folio = pymongo_db["portfolio_content"]
pymongo_col_user = pymongo_db["common_user"]


# Create your views here.
def index(request):
    try:
        answer_object = Answer.objects.filter()

        test_list = []
        for object in range(len(answer_object)):
            test_list.append(answer_object[object].content_id)
        my_dict = get_occurrence_count(test_list)
        sorted_dict = sorted(my_dict.items(), key=lambda item: item[1], reverse=True)
        sorted_dict = sorted_dict[:4]
        hot_id_list = []
        for i in range(len(sorted_dict)):
            hot_id_list.append(sorted_dict[:4][i][0])
        hot_toon_list = []
        hot_toon_img_list=[]
        for hot_id in hot_id_list:
            hot_toon = Content.objects.get(id=hot_id)
            hot_toon_img = hot_toon.content_img.split(',')[0][2:-1]
            hot_toon_list.append(hot_toon)
            hot_toon_img_list.append(hot_toon_img)
        # print('hot_toon_img_list:',hot_toon_img_list)
        hot_final_dict = zip(hot_id_list,hot_toon_list,hot_toon_img_list)
        hot_final_list = {"hot_final_dict":hot_final_dict}

        # print("hot_final_list:", hot_final_list)
        return render(request, 'base.html',hot_final_list)
    except:
        return render(request, 'base.html')

def get_occurrence_count(my_list):
  new_list = {}
  for i in my_list: 
    try: new_list[i] += 1
    except: new_list[i] = 1
  return(new_list)

def loading(request):
    return render(request, 'loading.html')

def loading3(request):
    return render(request, 'portfolio/loading3.html')

def mypage(request):
    ## 현재 로그인한 계정의 게시글만 보이도록 한정
    current_user = User.objects.get(username=request.user)
    current_content = Content.objects.filter(username=current_user)

    content_img_list = []
    content_link_list = []

    for img in range(len(current_content)):
        if len(current_content[img].content_img) <= 0:
            index = len(current_content[img].content_img)
        else:
            index = current_content[img].content_img[1:-1].find(',')
        content_first_img = current_content[img].content_img[2:index]
        content_img_list.append(content_first_img)          ## 이미지 경로값
        content_link_list.append(current_content[img].id)   ## 이미지 id값
    
    ## 최근에 작성한 글이 위에서 보이도록 reverse
    content_img_list.sort(reverse=True)
    content_link_list.sort(reverse=True)
    context = {"content_list": dict(zip(content_img_list, content_link_list)), "content_len":len(dict(zip(content_img_list, content_link_list)))}
    return render(request, 'portfolio/mypage.html', context)

def write_form(request):
    return render(request, 'portfolio/write.html')

def lounge(request):
    if request.user.is_authenticated == False:    ## 비로그인 상태에서 라운지 접속하기 위한 세팅
        lounge_content = Content.objects.filter() ## 모든 게시글을 불러온다
    else:
        current_user = User.objects.get(username=request.user)
        lounge_content = Content.objects.filter(~Q(username=current_user))

    lounge_img_list = []
    lounge_link_list = []

    for img in range(len(lounge_content)):
        index = lounge_content[img].content_img[1:-1].find(',')
        content_first_img = lounge_content[img].content_img[2:index]
        lounge_img_list.append(content_first_img)
        lounge_link_list.append(lounge_content[img].id)

    ## 최신글이 최상단에 나오도록 변경
    lounge_img_list = reversed(lounge_img_list)
    lounge_link_list = reversed(lounge_link_list)

    context = {"lounge_list": dict(zip(lounge_img_list, lounge_link_list))}

    return render(request, 'portfolio/lounge.html', context)

def content_detail(request, id):
    content = Content.objects.get(id=id)
    recommendation_result = content.reco_img
    context = {'content': content, "recommendation_result":recommendation_result}
    return render(request, 'portfolio/folio_content_detail.html', context)

def content_create(request):
    current_user = User.objects.get(username=request.user)
    current_user = str(current_user)
    current_content = Content.objects.filter(username=current_user)
    max_list = []
    iter_result = list(pymongo_col_folio.find())
    for i in iter_result:
        max_list.append(i['content_num'])
    print("max_list:", max_list)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            # redirect('portfolio:loading3')
            content = form.save(commit=False)
            if len(max_list) == 0:
                content.content_num = 1
            else:
                content.content_num = int(max_list[-1]) + 1
            print("-------form---")
            content.create_date = timezone.now()
            content.save()
            input_img = str(os.getcwd()) + "/media/" + str(content.input_img)
            txt = content.content
            # content.content_for_posting =
            if input_img == "/home/dhj9842/venv/mysite/media/":
                new_path_list = Txt2img.txt2img_func(txt, current_user)
            else:
                new_path_list = Img2img.img2img_func(input_img, txt, current_user)

            # print(f"new_path_list: {new_path_list}")
            # print(f"type new_path_list: {type(new_path_list)}")

            content.content_img = str(new_path_list)

            ################# content.reco_img = str(new_path_list)################


            content.save()

            return redirect('portfolio:mypage')
    else:
        form = ContentForm()
    context = {'form': form}
    return render(request, '/portflio/mypage.html', context)

def answer_create(request, content_id):
    current_user = User.objects.get(username=request.user)
    current_user = str(current_user)
    content = get_object_or_404(Content, pk=content_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.username = current_user
            answer.content = content
            answer.create_date = timezone.now()
            answer.context = request.POST.get('context')
            answer.save()
            return redirect('portfolio:content_detail', id=content.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'content': content, 'form': form}
    return render(request, 'portfolio:folio_content_detail', context)

templates/portfolio/folio_content_detail.html
{% extends 'base.html' %}
{% block content %}
{% load portfolio_filter %}
<header>
    <style>
.image-section {
    position: relative;
    overflow: hidden;
    display: flex;
    min-height: 50vh;
}

.second-loop-container {
    display: flex;
    flex-direction: row;
    width: 100%;
}

.images-wrapper {
    display: flex;
    flex-direction: row;
    gap: 2rem;

    position: absolute;
}

.image-container {
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    width: 440px;
    height: 440px;
}

.image-container img {
    object-fit: cover;
    min-width: 100%;
    min-height: 100%;
}

.item {
    position: absolute;
    color: white;
}

.mt-5 {
    margin-top:5rem !important;
}

.img_button {
	position:absolute;
	height:100%;
	top:0;
	border:none;
	padding:20px;
	color:#000;
	font-weight:800;
	font-size:24px;
	opacity:0.4;
}
#img_prev {
	left:0;
}
#img_next {
	right:0;
}
.img_button:hover {
	background-color:#222;
	color:#fff;
	opacity:0.6;
	cursor:pointer;
}
.img_button:focus {
	outline:0;
}





    </style>


</header>
<div class="container mt-5 my-3">

    <!-- subject -->
    <h2 class="border-bottom py-2">{{ content.subject }}</h2>


        <div class="row align-items-center mt-2 mt-md-0 pt-5 pt-md-4 pt-lg-0 pb-md-3 pb-lg-5 border-bottom py-2">
        <!-- image -->
        <section class="image-section">
            <div class="col-md-6 col-lg-5 offset-xl-1 mb-2 mb-md-0 pb-4 pb-md-0">
                <div class="images-wrapper image-container" id="images_test">
                    {% if content.content_img %}
                    {% for i in content.content_img|test %}
                    <img src="{{ i }}" alt="..."/>
                    {% endfor %}
                    {% else %}
                    No Image
                    {% endif %}
                    <button class="img_button" id="img_prev">&lang;</button>
                    <button class="img_button" id="img_next">&rang;</button>
                    <script src="/static/js/imageview.js"></script>
                </div>
            </div>

            <!-- content -->
            <div class="col-md-6 col-xl-5 offset-lg-1">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ content.content_for_posting }}</div>
                        <div class="d-flex justify-content-end">
                            <div class="badge bg-light text-dark p-2">
                                {{ content.create_date }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Post comments -->
    <section class="row align-items-center mt-2 mt-md-0 pt-5 pt-md-4 pt-lg-0 pb-md-3 pb-lg-5 border-bottom py-2">
        <h2 class="h1 text-center text-sm-start"> {{ content.answer_set.count }} comments</h2>

        <!-- Comment -->
        <div class="pb-3">
            <div class="card border-0 overflow-hidden mb-4">
                <div class="position-relative bg-repeat-0 bg-size-cover">
                    {% if content.answer_set.all %}
                    {% for answer in content.answer_set.all %}
                    <div class="d-flex align-items-center me-3">
                        <img src="/static/img/avatar/02.jpg" class="rounded-circle" width="48" alt="Avatar">
                        <div class="ps-3">
                            <h6 class="fw-semibold mb-0">{{ answer.username }}</h6>
                            <span class="fs-sm text-muted">{{ answer.create_date }}</span>
                            <p class="mb-0 pb-2">{{ answer.context }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <h6 class="fw-semibold mb-0">No Comment</h6>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if user.is_authenticated %}
        <!-- 비로그인 시에는 댓글작성 기능을 비활성화한다 -->
        <div class="py-4">
            <form action="{% url 'portfolio:answer_create' content.id %}" method="post">
                {% csrf_token %}
                <div class="card p-md-5 p-4 border-0 bg-secondary">
                    <div class="card-body w-100 mx-auto px-0" style="max-width: 746px;">
                        <label for="context" class="form-label fs-base">Comment</label>
                        <textarea name="context" id="context" class="form-control form-control-lg" rows="3"
                                  placeholder="댓글을 써주세요..." required></textarea>
                        <button type="submit" class="btn btn-lg btn-primary w-sm-auto w-100 mt-2">Post comment</button>
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
    </section>


    <!-- 추천알고리즘 넣기 -->
    <!-- {{content.content_img}} -->
    <!-- {{all_reco_img1}} -->

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
        {% if recommendation_result %}
        {% for img in recommendation_result %}
        <!-- Item -->
        <div class="col pb-3">
            <article class="card border-0 shadow-sm h-100">
                <div class="position-relative">
                    <img src="{{img}}" class="card-img-top" alt="Image">
                </div>
            </article>
        </div>
        {% endfor %}
        {% else %}
        No Recommendation
        {% endif %}
    </div>

    {% endblock %}

templates/portfolio/folio_content_detail222.html
{% extends 'base.html' %}
{% block content %}
{% load portfolio_filter %}
<header>
    <style>
.image-section {
    position: relative;
    overflow: hidden;
    display: flex;
    min-height: 50vh;
}

.second-loop-container {
    display: flex;
    flex-direction: row;
    width: 100%;
}

.images-wrapper {
    display: flex;
    flex-direction: row;
    gap: 2rem;

    position: absolute;
}

.image-container {
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    width: 440px;
    height: 440px;
}

.image-container img {
    object-fit: cover;
    min-width: 100%;
    min-height: 100%;
}

.item {
    position: absolute;
    color: white;
}

.mt-5 {
    margin-top:5rem !important;
}

.img_button {
	position:absolute;
	height:100%;
	top:0;
	border:none;
	padding:20px;
	color:#000;
	font-weight:800;
	font-size:24px;
	opacity:0.4;
}
#img_prev {
	left:0;
}
#img_next {
	right:0;
}
.img_button:hover {
	background-color:#222;
	color:#fff;
	opacity:0.6;
	cursor:pointer;
}
.img_button:focus {
	outline:0;
}





    </style>


</header>
<div class="container mt-5 my-3">

    <!-- subject -->
    <h2 class="border-bottom py-2">{{ content.subject }}</h2>


    <div class="row align-items-center mt-2 mt-md-0 pt-5 pt-md-4 pt-lg-0 pb-md-3 pb-lg-5 border-bottom py-2">
        <!-- image -->
        <section class="image-section">
            <div class="col-md-6 col-lg-5 offset-xl-1 mb-2 mb-md-0 pb-4 pb-md-0">
                <div class="images-wrapper image-container" id="images_test">
                    {% if content.content_img %}
                    {% for i in content.content_img|test %}
                    <img src="{{ i }}" alt="..."/>
                    {% endfor %}
                    {% else %}
                    No Image
                    {% endif %}
                    <button class="img_button" id="img_prev">&lang;</button>
                    <button class="img_button" id="img_next">&rang;</button>
                    <script src="/static/js/imageview.js"></script>
                </div>
            </div>

            <!-- content -->
            <div class="col-md-6 col-xl-5 offset-lg-1">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ content.content_for_posting }}</div>
                        <div class="d-flex justify-content-end">
                            <div class="badge bg-light text-dark p-2">
                                {{ content.create_date }}
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </section>
    </div>

    <!-- Post comments -->
    <section class="row align-items-center mt-2 mt-md-0 pt-5 pt-md-4 pt-lg-0 pb-md-3 pb-lg-5 border-bottom py-2">
        <h2 class="h1 text-center text-sm-start"> {{ content.answer_set.count }} comments</h2>

        <!-- Comment -->
        <div class="pb-3">
            <div class="card border-0 overflow-hidden mb-4">
                <div class="position-relative bg-repeat-0 bg-size-cover">
                    {% if content.answer_set.all %}
                    {% for answer in content.answer_set.all %}
                    <div class="d-flex align-items-center me-3">
                        <img src="/static/img/avatar/02.jpg" class="rounded-circle" width="48" alt="Avatar">
                        <div class="ps-3">
                            <h6 class="fw-semibold mb-0">{{ answer.username }}</h6>
                            <span class="fs-sm text-muted">{{ answer.create_date }}</span>
                            <p class="mb-0 pb-2">{{ answer.context }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <h6 class="fw-semibold mb-0">No Comment</h6>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if user.is_authenticated %}
        <!-- 비로그인 시에는 댓글작성 기능을 비활성화한다 -->
        <div class="py-4">
            <form action="{% url 'portfolio:answer_create' content.id %}" method="post">
                {% csrf_token %}
                <div class="card p-md-5 p-4 border-0 bg-secondary">
                    <div class="card-body w-100 mx-auto px-0" style="max-width: 746px;">
                        <label for="context" class="form-label fs-base">Comment</label>
                        <textarea name="context" id="context" class="form-control form-control-lg" rows="3"
                                  placeholder="댓글을 써주세요..." required></textarea>
                        <button type="submit" class="btn btn-lg btn-primary w-sm-auto w-100 mt-2">Post comment</button>
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
    </section>


    <!-- 추천알고리즘 넣기 -->
    <!-- {{content.content_img}} -->
    <!-- {{all_reco_img1}} -->

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">

    </div>

    {% endblock %}

templates/portfolio/folio_content_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-5">
    <h5 class="mt-5 my-3 border-bottom pb-2">Posting</h5>
    <form method="post" action="{% url 'portfolio:content_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">Title</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="username" class="form-label">Writer</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ user.username }}" readonly>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <div class="mb-3">
            <label for="input_img" class="form-label">Image</label>
            <input type="file" id="input_img" name="input_img" accept="image/png, image/jpeg">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/portfolio/mypage.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

{% extends "base.html" %}
{% block content %}
<!-- Profile -->
<!-- Testimonials (Slider) -->
{% load portfolio_filter %}

<style>
    a {text-decoration: none !important; color:#111;}
    a:hover {text-decoration: none !important; color:#111;}
</style>

<section class="container pb-5 mb-2 mb-md-4 mb-xl-5">
    <div class="row">
        <!-- Photo & Email -->
        <div class="col-md-5 mb-4 mb-md-0">
            <div class="card justify-content-center bg-light h-100 p-4 p-lg-5">
                <div class="card card-body card-hover card-center bg-light border-0 text-center mx-2">
                    <img src="/static/img/team/intoonteam.png" class="d-block rounded-circle mx-auto mb-3" width="162"
                         alt="Ralph Edwards">
                    <h5 class="fw-medium fs-lg mb-1">{{ user.username }}</h5>
                    <p class="fs-sm mb-3">{{ user.email }}</p>
                </div>
            </div>
        </div>

        <!-- Detail -->
        <div class="col-md-7">
            <div class="card border-0 shadow-sm p-4 p-xxl-5" style="height:100%">

                <!-- Slider prev/next buttons + Quotation mark -->
                <div class="d-flex justify-content-between pb-4 mb-2">
        <span class="btn btn-icon btn-primary btn-lg shadow-primary pe-none">
          <i class="bx bxs-quote-left"></i>
        </span>
                    <div class="d-flex justify-content-center">
                        <a href="#" class="btn btn-icon btn-outline-secondary btn-facebook btn-sm me-2">
                            <i class="bx bxl-facebook"></i>
                        </a>
                        <a href="#" class="btn btn-icon btn-outline-secondary btn-linkedin btn-sm me-2">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                        <a href="#" class="btn btn-icon btn-outline-secondary btn-twitter btn-sm">
                            <i class="bx bxl-twitter"></i>
                        </a>
                    </div>
                </div>

                <div class="swiper mt-n3 mt-md-0 pt-md-4 pt-lg-5 mx-n2" data-swiper-options='{
    "slidesPerView": 1,
    "spaceBetween": 8,
    "pagination": {
    "el": ".swiper-pagination",
    "clickable": true
    },
    "navigation": {
    "prevEl": "#prev-news",
    "nextEl": "#next-news"
    },
    "breakpoints": {
    "500": {
        "slidesPerView": 2
    },
    "700": {
        "slidesPerView": 2
    },
    "1000": {
        "slidesPerView": 2
    }
    }
}'>
                    <div class="swiper-wrapper">

                        <!-- 게시글 수 -->
                        <div class="swiper-slide h-auto pb-3">
                            <div class="card card-hov시er bg-light border-0 animation-on-hover h-100 mx-2">
                                <!--               check                 -->
                                <h3 class="display-4 text_primary mb-1 text-center">{{content_len}}</h3>
                                <div class="card-body fs-lg fw-semibold text-center">게시글 수</div>
                            </div>
                        </div>

                        <!-- 이미지 수 -->
<!--                        <div class="swiper-slide h-auto pb-3">-->
<!--                            <div class="card card-hover bg-light border-0 animation-on-hover h-100 mx-2">-->
<!--                                &lt;!&ndash;               check                 &ndash;&gt;-->
<!--                                <h3 class="display-4 text_primary mb-1 text-center">{{ content.content_img.count }}</h3>-->
<!--                                <div class="card-body fs-lg fw-semibold text-center">이미지 수</div>-->
<!--                            </div>-->
<!--                        </div>-->

                        <!-- 글쓰기 -->
                        <div class="swiper-slide h-auto pb-3">
                            <div class="card card-hover bg-light border-0 animation-on-hover h-100 mx-2">
                                <a href="{% url 'portfolio:write' %}" class="stretched-link">
                                    <img src="/static/img/idea.svg" width="48" alt="Bulb icon"
                                         class="d-block mb-4 mx-auto" alt="">
                                    <div class="position-relative">
                                        <div class="card-body fs-lg fw-semibold text-center">글쓰기</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>

                    <!-- Pagination (bullets) -->
                    <div class="swiper-pagination position-relative bottom-0 mt-2"></div>
                </div>
            </div>

</section>

<section class="container pb-3 mb-2 mb-md-2 mb-xl-5">
    <div class="row row-cols-lg-3 row-cols-sm-2 row-cols-1 gy-md-4 gy-2">

        {% if content_list %}
        {% for key, value in content_list.items %}
        <div class="col card-hover shadow-none bg-none position-relative mb-4 mb-lg-5">
            {% if key %}
            <img src="{{key}}" style="width:100%"/>
            {% else %}
            No Image
            {% endif %}

            <script src="/static/js/imageview.js"></script>
            <h3 class="h5 mt-4 mb-3 mb-lg-0" style="text-align:center">
                <!--      <a href="landing-medical.html" class="stretched-link">{{ content.subject }}</a>-->
                <a href="{% url 'portfolio:content_detail' value %}" class="stretched-link"></a>
                {{imsi.content_num}}  <!-- 삭제 필요 -->
                {{imsi.subject}}
            </h3>
        </div>

        {% endfor %}
        {% else %}
        <div>No Content</div>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/portfolio/write.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

{% extends 'base.html' %}
{% block content %}
<head>

</head>

<div class="container pt-5">
    <h5 class="mt-5 my-3 border-bottom pb-2">Posting</h5>

    <form method="post" id='testform' action="{% url 'portfolio:content_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->

        <!-- Title-->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}" placeholder="제목을 입력해 주세요" required>
        </div>
        <!--Writer -->
        <div class="mb-3" style="display:none">
            <label for="username" class="form-label">작성자</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ user.username }}" readonly>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">게시글 내용</label>
            <textarea placeholder="게시글 내용을 입력해 주세요" class="form-control" name="content_for_posting" id="content_for_posting" rows="10" required>{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <br>
        <div class="mb-3">
            <label for="content" class="form-label">모델 입력 내용</label>
            <textarea placeholder="생성할 이미지를 묘사해 주세요" class="form-control" name="content" id="content" rows="10" required>{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <div class="mb-3">
            <label for="input_img" class="form-label">이미지 선택(생성을 원하는 스타일이 있다면, 이미지 초안을 넣어주세요!!)</label><br>
            <input type="file" id="input_img" name="input_img" accept="image/png, image/jpeg">
        </div>
        <!--        <button type="submit" onclick="location.ref='https://192.168.0.27:8000/portfolio/loading3'" class="btn btn-primary" style="margin:auto, display:block">Write</button>-->

        <button type="submit" class="btn btn-primary" style="margin:auto, display:block">Create</button>
        <br>
    </form>

</div>



<script>
    (function (win, doc) {
    'use strict';
    if (!doc.querySelectorAll || !win.addEventListener) {
        // doesn't cut the mustard.
        return;
    }
    var forms = doc.querySelectorAll('form[method="post"]'),
        formcount = forms.length,
        i,
        submitting = false,
        checkForm = function (ev) {
            if (submitting) {
                ev.preventDefault();
            } else {
                submitting = true;
                this.appendChild(doc.createElement('progress'));
            }
        };
    for (i = 0; i < formcount; i = i + 1) {
        forms[i].addEventListener('submit', checkForm, false);
    }
}(this, this.document));

</script>
{% endblock %}