common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', views.index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=20, primary_key=True)
    profile_img_src = models.CharField(max_length=150, blank=True)
    profile_msg = models.TextField(max_length=300, blank=True)
    # birth_date = models.DateField(null=True, blank=True)


    def __str__(self):
        return self.username

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from common.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from .models import User

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()

            ### 회원가입 시, 자동 로그인
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)  # 사용자 인증
            # login(request, user, backend='django.contrib.auth.backends.ModelBackend') # 로그인
            return redirect('index')
    else: # Get 요청
        form = UserForm
    return render(request, 'common/signup.html', {'form':form})

templates/common/login.html
{% extends "base.html" %}
{% block content %}

<main class="page-wrapper">
    <!-- Page content -->
    <section class="position-relative h-100 pt-5 pb-4">

        <!-- Sign in form -->
        <div class="container d-flex flex-wrap justify-content-center h-100 pt-5">
            <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
                <h1 class="text-center">
                    <img class="text-center" src="/static/img/logo.png/" style="width:150px; text-align:center"/>
                </h1>
                <form method="post" action="{% url 'common:login' %}" class="needs-validation mb-2">
                    {% csrf_token %}
                    <div class="position-relative mb-4">
                        <label for="username" class="form-label fs-base">Username</label>
                        <input type="text" id="username" name="username" class="form-control form-control-lg" required
                            value="{{ form.username.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-4">
                        <label for="password" class="form-label fs-base">Password</label>
                        <div class="password-toggle">
                            <input type="password" id="password" name="password" class="form-control form-control-lg" required
                                value="{{ form.password.value|default_if_none:'' }}">
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox">
                                <span class="password-toggle-indicator"></span>
                            </label>
                        </div>
                    </div>
                    {% include "form_errors.html" %}
                    <div class="mb-4">
                        <div class="form-check">
                        <input type="checkbox" id="remember" class="form-check-input">
                        <label for="remember" class="form-check-label fs-base">Remember me</label>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}">
                    <button type="submit" class="btn btn-primary shadow-primary btn-lg w-100">로그인</button>
                </form>

                <hr class="my-4">

                <div class="row row-cols-1 row-cols-sm-2">
                    <div class="col mb-3">
                        <a href="#" class="btn btn-icon btn-secondary btn-google btn-lg w-100">
                            비밀번호찾기
                        </a>
                    </div>
                    <div class="col mb-3">
                        <a href="{% url 'common:signup' %}" class="btn btn-icon btn-secondary btn-facebook btn-lg w-100">
                            회원가입
                        </a>
                    </div>
                </div>
                <div class="w-100 align-self-end">
                    <p class="nav d-block fs-xs text-center pb-2 mb-0">
                    &copy; All rights reserved. Made by 
                    <a class="nav-link d-inline-block p-0" href="#" rel="noopener">IntoonTeam</a>
                    </p>    
                </div>
            </div>
            
        </div>
        
    </section>
</main>


<!-- Back to top button -->
<a href="#top" class="btn-scroll-top" data-scroll>
    <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
    <i class="btn-scroll-top-icon bx bx-chevron-up"></i>
</a>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}

<main class="page-wrapper">
    <!-- Page content -->
    <section class="position-relative h-100 pt-5 pb-4">

        <!-- Sign up form -->
        <div class="container d-flex flex-wrap justify-content-center h-100 pt-5">
            <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
                <h1 class="text-center">Create Account</h1>
                <p class="text-center pb-3 mb-3">Already have an account? <a href="account-signin.html">Sign in here.</a></p>
                <form method="post" action="{% url 'common:signup' %}" class="needs-validation" novalidate>
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="row">
                    <div class="col-sm-6">
                        <div class="position-relative mb-4">
                            <label for="name" class="form-label fs-base">Name</label>
                            <input type="text" class="form-control form-control-lg" name="username" id="username" required
                                   value="{{ form.username.value|default_if_none:'' }}">
                            <div class="invalid-feedback position-absolute start-0 top-100">Please enter your name!</div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="position-relative mb-4">
                            <label for="email" class="form-label fs-base">Email</label>
                            <input type="text" class="form-control form-control-lg" name="email" id="email" required
                                   value="{{ form.email.value|default_if_none:'' }}">
                            <div class="invalid-feedback position-absolute start-0 top-100">Please enter a valid email address!</div>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <label for="password" class="form-label fs-base">Password</label>
                        <div class="password-toggle">
                            <input type="password" class="form-control form-control-lg" name="password1" id="password1" required
                                   value="{{ form.password1.value|default_if_none:'' }}">
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox">
                                <span class="password-toggle-indicator"></span>
                            </label>
                            <div class="invalid-feedback position-absolute start-0 top-100">Please enter a password!</div>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <label for="password-confirm" class="form-label fs-base">Confirm password</label>
                        <div class="password-toggle">
                            <input type="password" class="form-control form-control-lg" name="password2" id="password2" required
                                   value="{{ form.password2.value|default_if_none:'' }}">
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox">
                                <span class="password-toggle-indicator"></span>
                            </label>
                            <div class="invalid-feedback position-absolute start-0 top-100">Please enter a password!</div>
                        </div>
                    </div>
                    </div>
                    <div class="mb-4">
                        <div class="form-check">
                            <input type="checkbox" id="terms" class="form-check-input">
                            <label for="terms" class="form-check-label fs-base">I agree to <a href="#">Terms &amp; Conditions</a></label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary shadow-primary btn-lg w-100">Sign up</button>
                </form>
                <!-- <hr class="my-4">
                <h6 class="text-center mb-4">Or sign up with your social network</h6>
                <div class="row row-cols-1 row-cols-sm-2">
                    <div class="col mb-3">
                        <a href="#" class="btn btn-icon btn-secondary btn-google btn-lg w-100">
                            <i class="bx bxl-google fs-xl me-2"></i>
                            Google
                        </a>
                    </div>
                    <div class="col mb-3">
                        <a href="#" class="btn btn-icon btn-secondary btn-facebook btn-lg w-100">
                            <i class="bx bxl-facebook fs-xl me-2"></i>
                            Facebook
                        </a>
                    </div>
                </div> -->
            </div>
            <div class="w-100 align-self-end">
                <p class="nav d-block fs-xs text-center pb-2 mb-0">
                &copy; All rights reserved. Made by 
                <a class="nav-link d-inline-block p-0" href="#" rel="noopener">IntoonTeam</a>
                </p>    
            </div>
        </div>
    </section>
</main>
{% endblock %}