common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', views.index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <title>#intoon</title>

    <!-- SEO Meta Tags-->
    <!-- <meta name="description" content="Silicon - Multipurpose Technology Bootstrap Template">
    <meta name="keywords" content="bootstrap, business, creative agency, construction, services, e-commerce, shopping cart, mobile app showcase, multipurpose, shop, ui kit, marketing, seo, landing, html5, css3, javascript, gallery, slider, touch, creative">
    <meta name="author" content="Createx Studio"> -->

    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon and Touch Icons-->
    <!-- <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png"> -->
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/head_logo.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/head_logo.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">
    <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#6366f1">
    <!-- <link rel="shortcut icon" href="/static/favicon/favicon.ico"> -->
    <link rel="shortcut icon" href="/static/img/head_logo.png">
    <meta name="msapplication-TileColor" content="#080032">
    <meta name="msapplication-config" content="/static/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- Vendor Styles-->
    <link rel="stylesheet" media="screen" href="/static/vendor/boxicons/css/boxicons.min.css"/>
    <link rel="stylesheet" media="screen" href="/static/vendor/swiper/swiper-bundle.min.css"/>
    <!-- Main Theme Styles + Bootstrap-->
    <link rel="stylesheet" media="screen" href="/static/css/theme.min.css">

    <!-- Page loading styles -->
    <style>
      .page-loading {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        -webkit-transition: all .4s .2s ease-in-out;
        transition: all .4s .2s ease-in-out;
        background-color: #fff;
        opacity: 0;
        visibility: hidden;
        z-index: 9999;
      }
      .dark-mode .page-loading {
        background-color: #0b0f19;
      }
      .page-loading.active {
        opacity: 1;
        visibility: visible;
      }
      .page-loading-inner {
        position: absolute;
        top: 50%;
        left: 0;
        width: 100%;
        text-align: center;
        -webkit-transform: translateY(-50%);
        transform: translateY(-50%);
        -webkit-transition: opacity .2s ease-in-out;
        transition: opacity .2s ease-in-out;
        opacity: 0;
      }
      .page-loading.active > .page-loading-inner {
        opacity: 1;
      }
      .page-loading-inner > span {
        display: block;
        font-size: 1rem;
        font-weight: normal;
        color: #9397ad;
      }
      .dark-mode .page-loading-inner > span {
        color: #fff;
        opacity: .6;
      }
      .page-spinner {
        display: inline-block;
        width: 2.75rem;
        height: 2.75rem;
        margin-bottom: .75rem;
        vertical-align: text-bottom;
        border: .15em solid #b4b7c9;
        border-right-color: transparent;
        border-radius: 50%;
        -webkit-animation: spinner .75s linear infinite;
        animation: spinner .75s linear infinite;
      }
      .dark-mode .page-spinner {
        border-color: rgba(255,255,255,.4);
        border-right-color: transparent;
      }
      @-webkit-keyframes spinner {
        100% {
          -webkit-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
      @keyframes spinner {
        100% {
          -webkit-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
    </style>

    <!-- Theme mode -->
    <script>
      let mode = window.localStorage.getItem('mode'),
          root = document.getElementsByTagName('html')[0];
      if (mode !== null && mode === 'dark') {
        root.classList.add('dark-mode');
      } else {
        root.classList.remove('dark-mode');
      }
    </script>

    <!-- Page loading scripts -->
    <script>
      (function () {
        window.onload = function () {
          const preloader = document.querySelector('.page-loading');
          preloader.classList.remove('active');
          setTimeout(function () {
            preloader.remove();
          }, 1000);
        };
      })();
    </script>
  </head>

<body>
    <!-- Page loading spinner -->
    <div class="page-loading active">
      <div class="page-loading-inner">
        <div class="page-spinner"></div><span>Loading...</span>
      </div>
    </div>

    <main class="page-wrapper">
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->

    {% block content %}

    {% include "main/hero.html" %}           <!-- 배너 이미지 -->
    {% include "main/main.html" %}           <!-- main skill -->
    {% include "main/portfolio_list.html" %} <!-- Hot TOONS -->
    {% include "main/more_feature.html" %}   <!-- about main skill -->
    {% include "main/stack.html" %}          <!-- 사용된 기술스택 -->
    {% include "main/footer.html" %}
    
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    </main>

    <!-- Back to top button -->
    <a href="#top" class="btn-scroll-top" data-scroll>
      <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
      <i class="btn-scroll-top-icon bx bx-chevron-up"></i>
    </a>

    <!-- Vendor Scripts -->
    <script src="/static/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    <script src="/static/vendor/rellax/rellax.min.js"></script>
    <script src="/static/vendor/@lottiefiles/lottie-player/dist/lottie-player.js"></script>
    <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
    <!-- Main Theme Script -->
    <script src="/static/js/theme.min.js"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/loading.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <style>


<!--        -->
        * {
            border: 0;
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        :root {
            --hue: 223;
            --bg: hsl(var(--hue),90%,95%);
            --fg: hsl(var(--hue),90%,5%);
            --primary: hsl(var(--hue),90%,50%);
            --trans-dur: 0.3s;
            font-size: calc(16px + (24 - 16) * (100vw - 320px) / (1280 - 320));
        }
        body {
<!--            background-color: var(&#45;&#45;bg);-->
<!--            color: var(&#45;&#45;fg);-->
            font: 1em/1.5 sans-serif;
            height: 100vh;
            display: grid;
            place-items: center;
<!--            transition: background-color var(&#45;&#45;trans-dur);-->
        }
        main {
            padding: 1.5em 0;
        }
        .pl {
            display: block;
            overflow: visible;
            width: 8em;
            height: 8em;
        }
        .pl__ring {
            stroke: hsla(var(--hue),90%,5%,0.1);
            transition: stroke var(--trans-dur);
        }
        .pl__worm {
            stroke: var(--primary);
            transform-origin: 64px 64px;
            visibility: hidden;
        }
        .pl__worm--moving {
            animation: worm 8s linear;
            visibility: visible;
        }

        /* Dark theme */
        @media (prefers-color-scheme: dark) {
        :root {
            --bg: hsl(var(--hue),90%,5%);
            --fg: hsl(var(--hue),90%,95%);
        }
        .pl__ring {
            stroke: hsla(var(--hue),90%,95%,0.1);
        }
        }

        /* Animations */
        @keyframes worm {
        from {
            stroke-dasharray: 22 307.86 22;
            transform: rotate(0);
        }
        to {
            stroke-dasharray: 2 347.86 2;
            transform: rotate(4turn);
        }

        }

        button {
            --background: #2F3545;
            --shadow: 0 2px 8px -1px #{rgba(#151924, .32)};
            --shadow-hover: 0 4px 20px -2px #{rgba(#151924, .5)};
        }



        .blackLightbox {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            position: fixed;
            left: 0;
            top: 0;
            z-index: 2;
            display: none;
            filter: alpha(opacity=70);
        }



        .loading_main {
            visibility: visible;
            height: 600px;
            width: 820px;
            margin: auto;
            margin-top : 50px;
            padding: 20px;
            background: white;
            border-radius: 20px 0 20px 0;
        }
    </style>
</head>

<body>
    <!-- 배경   -->
    <div id="loginview" class="blackLightbox" style="display: block;">
        <!-- 로딩 박스 (화이트)       -->
        <div class="loading_main">

            <div align="center">
                <main>
                  <svg class="pl" viewBox="0 0 120 120" width="100px" height="100px" xmlns="http://www.w3.org/2000/svg">
                    <g fill="none" stroke-linecap="round" stroke-width="16" transform="rotate(-90,64,64)">
                      <circle class="pl__ring" r="56" cx="64" cy="64" stroke="#ddd" />
                      <circle class="pl__worm pl__worm--moving" r="56" cx="64" cy="64" stroke="currentColor" stroke-dasharray="22 307.86 22" data-worm />
                    </g>
                    <g data-particles></g>
                  </svg>
                </main>
            </div><br>

            <div align="center">

                <a href="" onclick=alert('로딩중') >
                    <img src='/static/img/image.png' style="width:150px; height:150px;" align="center">
                </a>
            </div>
            <div align="center">
                <br>
                <button class="btn btn-primary" onclick ="location.href='http://192.168.0.27:8000/portfolio/mypage'" style="height:45px; width:150px; background:white; text-align:center; text-weight:bold; font-size:20px; border:3px solid #5858FA; padding:8px 15px 13px 15px; margin-bottom:30px; cursor:pointer;" type="submit">Cancle</button>
            </div>

        </div>
    </div>
<script>
    window.addEventListener("DOMContentLoaded",() => {
  const dp = new DecayingPreloader(".pl");
});

class DecayingPreloader {
  particles = [];
  totalParticles = 120;
  replayTimeout = null;

  constructor(el) {
    this.el = document.querySelector(el);
    this.particleGroup = this.el?.querySelector("[data-particles]");
    this.worm = this.el?.querySelector("[data-worm]");

    this.init();
  }
  init() {
    this.spawnParticles(this.totalParticles);
    this.worm?.addEventListener("animationend",this.replayParticles.bind(this));
  }
  createParticle(x,y,r,delay) {
    const particle = new DecayParticle(x,y,r,delay);
    this.particleGroup?.appendChild(particle.g);
    // animation params
    particle.gAnimation = particle.g.animate(
      [
        { transform: `translate(${particle.x}px,0)` },
        { transform: `translate(${particle.x + particle.dx}px,0)` },
      ],
      { delay: particle.delay, duration: particle.duration, easing: "linear" }
    );
    particle.cAnimation = particle.c.animate(
      [
        { opacity: 1, transform: `translate(0,${particle.y}px) scale(1)` },
        { opacity: 1, transform: `translate(0,${particle.y + particle.dy}px) scale(0)` },
      ],
      { delay: particle.delay, duration: particle.duration, easing: "ease-in" }
    );
    // finally create the particle
    this.particles.push(particle);
  }
  replayParticles() {
    const movingClass = "pl__worm--moving";
    const timeout = 800;
    // retrigger the worm animation
    this.worm.classList.remove(movingClass);
    clearTimeout(this.replayTimeout);

    this.replayTimeout = setTimeout(() => {
      this.worm.classList.add(movingClass);
      // restart the particles
      this.particles.forEach(particle => {
        particle.gAnimation.finish();
        particle.gAnimation.play();
        particle.cAnimation.finish();
        particle.cAnimation.play();
      });
    },timeout);
  }
  spawnParticles(count = 1) {
    const centerXY = 64;
    const radius = 56;
    const loops = 4;
    const maxDelayPerLoop = 2000;
    const particlesPerLoop = Math.round(this.totalParticles / loops);
    const angleOffset = -2;
    const particleRadius = 7;

    for (let c = 0; c < count; ++c) {
      // place along the ring
      const percent = Utils.easeInOutCubic(c % particlesPerLoop / particlesPerLoop);
      const angle = 360 * percent + angleOffset;
      const x = centerXY + radius * Math.sin(Utils.degToRad(angle));
      const y = centerXY - radius * Math.cos(Utils.degToRad(angle));
      const loopsCompleted = Math.floor(c / particlesPerLoop);
      const delay = maxDelayPerLoop * percent + maxDelayPerLoop * loopsCompleted;

      this.createParticle(x,y,particleRadius,delay);
    }
  }
}
class DecayParticle {
  duration = 500;
  dx = Utils.randomFloat(-16,16);
  dy = Utils.randomFloat(32,64);
  // group
  gAnimation = null;
  // circle
  cAnimation = null;

  constructor(x = 0,y = 0,r = 1,delay = 0) {
    this.x = x;
    this.y = y;
    this.r = r;
    this.delay = delay;
    // namespace
    const ns = "http://www.w3.org/2000/svg";
    // group to move horizontally in the animation
    const g = document.createElementNS(ns,"g");
    g.setAttributeNS(null,"transform",`translate(${x},0)`);
    // circle to move vertically in the animation
    const circle = document.createElementNS(ns,"circle");
    circle.setAttributeNS(null,"opacity","0");
    circle.setAttributeNS(null,"r",`${this.r}`);
    circle.setAttributeNS(null,"transform",`translate(0,${y})`);
    circle.setAttributeNS(null,"fill","var(--primary)");

    this.g = g;
    this.c = circle;

    this.g.appendChild(this.c);
  }
}
class Utils {
  static degToRad(deg) {
    return deg * Math.PI / 180;
  }
  // ease methods from https://gist.github.com/gre/1650294
  static easeInOutCubic(t) {
    return t < 0.5 ? 4 * t ** 3 : (t - 1) * (2 * t - 2) * (2 * t - 2) + 1;
  }
  static randomFloat(min = 0,max = 2**32) {
    const percent = crypto.getRandomValues(new Uint32Array(1))[0] / 2**32;
    const relativeValue = (max - min) * percent;
    const plusMin = min + relativeValue;

    return +(plusMin).toFixed(3);
  }
}
</script>
</body>

templates/navbar.html
<!-- Navbar -->
<!-- Remove "fixed-top" class to make navigation bar scrollable with the page -->
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
    <div class="container px-3">
        <a href="/" class="navbar-brand pe-3">
            <img src="/static/img/logo.png" width="70" alt="Burger">
        </a>

        <div id="navbarNav" class="offcanvas offcanvas-end">
            <div class="offcanvas-header border-bottom">
                <h5 class="offcanvas-title">Menu</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="/portfolio/lounge/" class="nav-link">Lounge</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown"
                           aria-current="page">My Page</a>
                        <div class="dropdown-menu p-0">
                            <div class="d-lg-flex">
                                <!-- <div class="mega-dropdown-column bg-position-center bg-repeat-0 bg-size-cover rounded-3 rounded-end-0"
                                     style="background-color: #cecdf9; margin: -1px;"></div> -->
                                <div class="mega-dropdown-column pt-lg-3 pb-lg-4">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="/portfolio/mypage/" class="dropdown-item">{{user}}</a></li>
                                        <li><a href="/portfolio/write/" class="dropdown-item">Create Image</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}

                </ul>
            </div>
            <div class="offcanvas-header border-top">
                {% if user.is_authenticated %}
                <a href="{% url 'common:logout' %}" class="btn btn-primary w-100" rel="noopener">
                    Log out
                </a>
                {% else %}
                <a href="{% url 'common:login' %}" class="btn btn-primary w-100" rel="noopener">
                    Log In
                </a>
                {% endif %}
            </div>
        </div>
        <div class="form-check form-switch mode-switch pe-lg-1 ms-auto me-4" data-bs-toggle="mode">
            <input type="checkbox" class="form-check-input" id="theme-mode">
            <label class="form-check-label d-none d-sm-block" for="theme-mode">Light</label>
            <label class="form-check-label d-none d-sm-block" for="theme-mode">Dark</label>
        </div>
        <button type="button" class="navbar-toggler" data-bs-toggle="offcanvas" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {% if user.is_authenticated %}
        <a href="{% url 'common:logout' %}" class="btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex"
           rel="noopener">
            Log out
        </a>
        {% else %}
        <a href="{% url 'common:login' %}" class="btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex"
           rel="noopener">
            Log In
        </a>
        {% endif %}
    </div>
</header>